version: '2'
services:
#### Database ####
  db:
      image: mysql:5.6
      ports:
          - 3306:3306
      environment:
          - MYSQL_ROOT_PASSWORD=megaloDocker!
      volumes:
          - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
          - ./docker/mysql:/var/lib/mysql
#### nginX ####
  nginx:
      build: ./docker/nginx
      ports:
          - 80:80
      links:
          - api
      volumes_from:
          - api
      volumes:
          - ./docker/logs/nginx/:/var/log/nginx

#### phpMyAdmin ####
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
          - 8080:80
      links:
          - db
      environment:
        PMA_HOST: db
        PMA_PORT: 3306

#### Websites Symfony 2.8 ####
  api:
      build: ./docker/php7-fpm
      expose:
          - 9000
      volumes:
          - ./:/var/www/api-platform/:cached
          - ./docker/logs/:/var/www/api-platform
      links:
          - db

